# Generated by Django 2.2.4 on 2019-10-27 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191027_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='rollno',
        ),
    ]
