# Generated by Django 2.2.4 on 2019-10-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_rollno'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hint',
            field=models.TextField(default='hint', max_length=100),
            preserve_default=False,
        ),
    ]
