# Generated by Django 2.2.4 on 2019-11-07 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_hint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
